Repository jdalrymple/gitbeaker, pull requests merged in 2020-04, with the labels that each got.

#647 feat: Updated an API parameter for GitLab 12.9
  packages/gitbeaker-core/src/services/ContainerRegistry.ts
Labels: breaking

#696 Update CHANGELOG.md
  CHANGELOG.md
  README.md
  lerna.json
Labels: skip-release

#697 Adding integration tests for the browser usage
  .autorc.yml
  .eslintrc.yml
  .gitlab-ci.yml
  README.md
  jest.config.base.js
  jest.config.js
  package.json
  packages/gitbeaker-browser/jest.config.js
  packages/gitbeaker-browser/package.json
  packages/gitbeaker-browser/src/index.ts
  packages/gitbeaker-browser/test/integration/assets/test-import.html
  packages/gitbeaker-browser/test/integration/index.ts
  packages/gitbeaker-browser/tsconfig.json
  packages/gitbeaker-cli/package.json
  packages/gitbeaker-core/package.json
  packages/gitbeaker-node/package.json
  packages/gitbeaker-requester-utils/package.json
  yarn.lock
Labels: enhancement, needs review

#712 Updating agent property based on new changes in Got
  packages/gitbeaker-browser/src/KyRequester.ts
  packages/gitbeaker-browser/test/unit/KyRequester.ts
  packages/gitbeaker-node/src/GotRequester.ts
  packages/gitbeaker-node/test/unit/GotRequester.ts
  packages/gitbeaker-requester-utils/src/RequesterUtils.ts
  packages/gitbeaker-requester-utils/test/unit/RequesterUtils.ts
Labels: bug

#711 Adding CLI Integration Tests
  .gitlab-ci.yml
  jest.config.js
  lerna.json
  package.json
  packages/gitbeaker-browser/jest.config.js
  packages/gitbeaker-browser/src/index.ts
  packages/gitbeaker-browser/test/integration/index.ts
  packages/gitbeaker-cli/jest.config.js
  packages/gitbeaker-cli/src/index.ts
  packages/gitbeaker-cli/test/integration/index.ts
  packages/gitbeaker-core/jest.config.js
  packages/gitbeaker-node/jest.config.js
  packages/gitbeaker-node/package.json
  packages/gitbeaker-node/src/index.ts
  packages/gitbeaker-node/test/integration/services/ApplicationSettings.ts
  packages/gitbeaker-node/test/integration/services/Commits.ts
  packages/gitbeaker-node/test/integration/services/Groups.ts
  packages/gitbeaker-node/test/integration/services/Issues.ts
  packages/gitbeaker-node/test/integration/services/IssuesStatistics.ts
  packages/gitbeaker-node/test/integration/services/Labels.ts
  packages/gitbeaker-node/test/integration/services/License.ts
  packages/gitbeaker-node/test/integration/services/NotificationSettings.ts
  packages/gitbeaker-node/test/integration/services/Projects.ts
  packages/gitbeaker-node/test/integration/services/PushRules.ts
  packages/gitbeaker-node/test/integration/services/Snippets.ts
  packages/gitbeaker-node/test/integration/services/UserGPGKeys.ts
  packages/gitbeaker-node/test/integration/services/Users.ts
  packages/gitbeaker-requester-utils/jest.config.js
  packages/gitbeaker-requester-utils/src/RequesterUtils.ts
  yarn.lock
Labels: bug

#606 feats: adds options interface for MergeRequest.all()
  packages/gitbeaker-core/src/services/MergeRequests.ts
Labels: enhancement

#737 Add types field to node and browser package.json
  packages/gitbeaker-browser/package.json
  packages/gitbeaker-core/package.json
  packages/gitbeaker-node/package.json
Labels: bug
