Repository jdalrymple/gitbeaker, pull requests merged in 2020-07, with the labels that each got.

#925 :up: create todos for issues
  packages/gitbeaker-core/src/services/Todos.ts
Labels: breaking

#795 Fixing up the Type exports for all the distributed libraries
  README.md
  packages/gitbeaker-browser/package.json
  packages/gitbeaker-cli/src/index.ts
  packages/gitbeaker-requester-utils/src/RequesterUtils.ts
  yarn.lock
Labels: bug, canary

#956 Fixing type definitions for optional arguments
  packages/gitbeaker-core/src/services/EpicNotes.ts
  packages/gitbeaker-core/src/services/IssueNotes.ts
  packages/gitbeaker-core/src/services/MergeRequestNotes.ts
  packages/gitbeaker-core/src/services/ProjectSnippetNotes.ts
Labels: bug
