Repository jdalrymple/gitbeaker, pull requests merged in 2020-12, with the labels that each got.

#1352 Export the APIMap through a compile-time replacement
  packages/gitbeaker-browser/src/index.ts
  packages/gitbeaker-cli/src/cli.ts
  packages/gitbeaker-core/package.json
  packages/gitbeaker-core/rollup.config.js
  packages/gitbeaker-core/scripts/generate.ts
  packages/gitbeaker-core/src/index.ts
  packages/gitbeaker-core/src/services/Environments.ts
  packages/gitbeaker-core/src/services/Groups.ts
  packages/gitbeaker-node/src/index.ts
  packages/gitbeaker-requester-utils/src/RequesterUtils.ts
  yarn.lock
Labels: breaking, canary, needs review

#1376 Fix table markdown format in README
  README.md
Labels: documentation

#1386 Implement "Commits.signature" method
  packages/gitbeaker-core/src/services/Commits.ts
Labels: feature

#1413 Fixing incorrect scoping of the createRequesterFn function
  packages/gitbeaker-core/src/services/Commits.ts
  packages/gitbeaker-requester-utils/src/RequesterUtils.ts
  packages/gitbeaker-requester-utils/test/unit/RequesterUtils.ts
Labels: bug
