Repository jdalrymple/gitbeaker, pull requests merged in 2020-05, with the labels that each got.

#760 Updating the pagination documentation
  README.md
  lerna.json
Labels: documentation

#780 Fix: Update DELETE method to POST in todos.done()
  packages/gitbeaker-core/src/services/Todos.ts
Labels: bug

#797 Project upload is not formatting form-data correctly
  packages/gitbeaker-core/src/services/ProjectImportExport.ts
  packages/gitbeaker-core/src/services/Projects.ts
Labels: bug

#796 Update typing to specify that the path or name property must be passed
  packages/gitbeaker-core/src/services/Projects.ts
  packages/gitbeaker-core/test/unit/services/Projects.ts
Labels: documentation

#801 Feature: Arbitrary parameters for Projects.search
  packages/gitbeaker-core/src/services/Projects.ts
Labels: enhancement
