Repository jdalrymple/gitbeaker, pull requests merged in 2021-11, with the labels that each got.

#2185 Add ability to request merged_yaml from the Gitlab Lint API
  packages/core/src/resources/Lint.ts
  packages/node/test/integration/resources/Lint.ts
Labels: feature

#2205 Renamed parameter
  packages/core/src/resources/MergeRequestDiscussions.ts
Labels: bug

#2195 Swap mime-types with mime for a smaller pkg size
  packages/core/package.json
  packages/core/src/resources/PackageRegistry.ts
  packages/core/src/resources/ProjectImportExport.ts
  packages/core/src/resources/Projects.ts
  yarn.lock
Labels: technical debt

#2222 Add support for CI lint with namespace context
  packages/core/src/resources/Lint.ts
  packages/node/test/integration/resources/Lint.ts
Labels: feature
