Repository jdalrymple/gitbeaker, pull requests merged in 2021-05, with the labels that each got.

#1726 Change Issues.unsubscribe to a POST operation instead of DELETE
  packages/gitbeaker-core/src/services/Issues.ts
  packages/gitbeaker-core/test/unit/services/Issues.ts
Labels: bug

#1766 add Jobs.showPipelineBridges
  packages/gitbeaker-core/src/services/Jobs.ts
  packages/gitbeaker-core/test/unit/services/Jobs.ts
Labels: feature

#1775 Updating all dependencies
  .lintstagedrc.yml
  .prettierrc.yml
  package.json
  packages/gitbeaker-browser/package.json
  packages/gitbeaker-cli/package.json
  packages/gitbeaker-cli/src/cli.ts
  packages/gitbeaker-core/package.json
  packages/gitbeaker-core/src/infrastructure/RequestHelper.ts
  packages/gitbeaker-core/src/infrastructure/Utils.ts
  packages/gitbeaker-core/src/services/GroupMilestones.ts
  packages/gitbeaker-core/src/services/Jobs.ts
  packages/gitbeaker-core/src/services/ProjectMilestones.ts
  packages/gitbeaker-core/src/services/Repositories.ts
  packages/gitbeaker-core/src/services/RepositoryFiles.ts
  packages/gitbeaker-core/src/templates/ResourceMilestones.ts
  packages/gitbeaker-node/package.json
  packages/gitbeaker-requester-utils/package.json
  yarn.lock
Labels: dependencies

#1781 Fixing weird request format for discussions
  packages/gitbeaker-core/src/infrastructure/RequestHelper.ts
  packages/gitbeaker-core/src/services/CommitDiscussions.ts
  packages/gitbeaker-core/src/services/EpicDiscussions.ts
  packages/gitbeaker-core/src/services/IssueDiscussions.ts
  packages/gitbeaker-core/src/services/MergeRequestDiscussions.ts
  packages/gitbeaker-core/src/services/ProjectSnippetDiscussions.ts
  packages/gitbeaker-core/src/templates/ResourceDiscussions.ts
  packages/gitbeaker-core/test/unit/templates/ResourceDiscussions.ts
Labels: bug
