Repository jdalrymple/gitbeaker, pull requests merged in 2021-12, with the labels that each got.

#2255 Updating Tag.create function to match latest API
  packages/core/src/resources/Tags.ts
  packages/core/test/unit/resources/Tags.ts
Labels: breaking

#2256 Changing CI script to utilize workspaces to temporarily store build files
  .circleci/config.yml
Labels: bug

#2262 Fix typing for the particpants and relatedMergeRequests functions within the Issues API
  packages/core/src/resources/Issues.ts
Labels: bug

#2290 Add sponser information to the README
  README.md
Labels: documentation
