Repository jdalrymple/gitbeaker, pull requests merged in 2023-12, with the labels that each got.

#3483 Updating all package deps
  package.json
  packages/cli/package.json
  packages/core/package.json
  packages/core/src/infrastructure/RequestHelper.ts
  packages/requester-utils/package.json
  packages/rest/package.json
  yarn.lock
Labels: type:dependencies

#3482 Fix a couple of types in Users and PersonalAccessTokens resources
  packages/core/src/resources/PersonalAccessTokens.ts
  packages/core/src/resources/Users.ts
Labels: type:bug

#3479 Updating MergeRequestDiscussion's endpoints
  packages/core/src/templates/ResourceDiscussions.ts
  packages/core/test/unit/resources/MergeRequestDiscussions.ts
  packages/core/test/unit/templates/ResourceDiscussions.ts
Labels: type:bug

#3488 add detailed_merge_status to MergeRequestSchema
  packages/core/src/resources/MergeRequests.ts
Labels: type:technical debt

#3491 fix: incorrect `noteable_type` type for `MergeRequest`
  packages/core/src/resources/MergeRequestNotes.ts
  packages/core/src/templates/ResourceDiscussions.ts
  packages/core/src/templates/ResourceNotes.ts
Labels: type:bug

#3496 Add explicit error types for easier debugging
  .github/ISSUE_TEMPLATE/1-bug.md
  packages/requester-utils/src/GitbeakerError.ts
  packages/requester-utils/src/index.ts
  packages/rest/README.md
  packages/rest/src/Requester.ts
  packages/rest/test/unit/Requester.ts
  yarn.lock
Labels: type:technical debt

#3498 Types - Add more options to MR create
  packages/core/src/resources/MergeRequests.ts
Labels: type:types

#3497 Add back isForm when setting position within the create Discussions API
  packages/core/src/templates/ResourceDiscussions.ts
  packages/core/test/unit/templates/ResourceDiscussions.ts
Labels: type:bug

#3502 Updating badges
  packages/cli/README.md
  packages/core/README.md
  packages/requester-utils/README.md
  packages/rest/README.md
Labels: type:documentation

#3504 Updating sponsors header
  .husky/pre-commit
  README.md
  packages/cli/README.md
  packages/core/README.md
  packages/requester-utils/README.md
  packages/rest/README.md
Labels: type:documentation

#3503 Fixing Users.edit HTTP Method
  packages/core/src/resources/Users.ts
  packages/core/test/__mocks__/RequestHelper.ts
  packages/core/test/unit/resources/GeoSites.ts
  packages/core/test/unit/resources/GitlabPages.ts
  packages/core/test/unit/resources/GroupEpicBoards.ts
  packages/core/test/unit/resources/InstanceLevelCICDVariables.ts
  packages/core/test/unit/resources/Users.ts
  packages/core/test/unit/templates/ResourceIssueBoards.ts
Labels: type:bug

#3501 Restructuring the AccessLevel enum
  .eslintrc.yml
  packages/cli/src/utils.ts
  packages/core/src/constants.ts
  packages/core/src/index.ts
  packages/core/src/resources/BroadcastMessages.ts
  packages/core/src/resources/GroupAccessRequests.ts
  packages/core/src/resources/GroupAccessTokens.ts
  packages/core/src/resources/GroupInvitations.ts
  packages/core/src/resources/GroupLDAPLinks.ts
  packages/core/src/resources/GroupMemberRoles.ts
  packages/core/src/resources/GroupMembers.ts
  packages/core/src/resources/GroupSAMLLinks.ts
  packages/core/src/resources/Groups.ts
  packages/core/src/resources/ProjectAccessRequests.ts
  packages/core/src/resources/ProjectAccessTokens.ts
  packages/core/src/resources/ProjectInvitations.ts
  packages/core/src/resources/ProjectMembers.ts
  packages/core/src/resources/Projects.ts
  packages/core/src/resources/ProtectedBranches.ts
  packages/core/src/resources/ProtectedTags.ts
  packages/core/src/resources/Users.ts
  packages/core/src/templates/ResourceAccessRequests.ts
  packages/core/src/templates/ResourceAccessTokens.ts
  packages/core/src/templates/ResourceInvitations.ts
  packages/core/src/templates/ResourceMembers.ts
  packages/core/src/templates/ResourceProtectedEnvironments.ts
  packages/core/test/unit/resources/ProtectedTags.ts
  packages/rest/src/index.ts
  packages/rest/test/e2e/browser/index.ts
  yarn.lock
Labels: type:enhancement
