Repository jdalrymple/gitbeaker, pull requests merged in 2023-11, with the labels that each got.

#3454 Add `addLabels` en `removeLabels` properties to update mr call
  packages/core/src/resources/MergeRequests.ts
Labels: type:bug

#3456 Fix typing on Project.show methods
  packages/cli/package.json
  packages/core/package.json
  packages/core/src/resources/Projects.ts
  packages/requester-utils/package.json
  packages/rest/package.json
Labels: type:bug

#3457 Dependencies
  .all-contributorsrc
  .gitlab-ci.yml
  package.json
  packages/cli/package.json
  packages/core/package.json
  packages/core/src/infrastructure/RequestHelper.ts
  packages/core/src/infrastructure/Utils.ts
  packages/requester-utils/package.json
  packages/rest/package.json
  yarn.lock
Labels: type:dependencies

#3459 Add rotate to PersonalAccessTokens resource
  packages/core/src/resources/PersonalAccessTokens.ts
Labels: type:feature

#3458 Add creation for service accounts on selfhosted instances
  packages/core/README.md
  packages/core/src/resources/Gitlab.ts
  packages/core/src/resources/GroupServiceAccounts.ts
  packages/core/src/resources/ServiceAccounts.ts
  packages/core/src/resources/index.ts
  packages/rest/src/index.ts
Labels: type:feature

#3460 Add service account API test updates
  packages/rest/test/e2e/browser/index.ts
Labels: type:testing

#3475 Update commitId to be of type string
  packages/core/src/resources/CommitDiscussions.ts
Labels: type:documentation

#3474 Fixing Group SAML Links API for the show and remove methods
  packages/core/src/resources/GroupSAMLLinks.ts
Labels: type:bug

#3473 Fixing position argument naming
  packages/core/src/resources/GroupVariables.ts
Labels: type:bug
