Repository jdalrymple/gitbeaker, pull requests merged in 2023-10, with the labels that each got.

#3418 Add Blob to RepositoryFiles.showRaw response type
  packages/core/src/resources/RepositoryFiles.ts
Labels: type:bug

#3422 docs/FAQ.md: Add js code fence syntax
  docs/FAQ.md
Labels: type:documentation

#3425 Adding missed push rule attributes
  packages/core/src/templates/ResourcePushRules.ts
Labels: type:bug

#3424 Add support for the SearchAdmin, GroupEpicBoards, GeoSites and CodeSuggestion APIs
  packages/core/src/resources/CodeSuggestions.ts
  packages/core/src/resources/GeoSites.ts
  packages/core/src/resources/Gitlab.ts
  packages/core/src/resources/GroupEpicBoards.ts
  packages/core/src/resources/SearchAdmin.ts
  packages/core/src/resources/index.ts
  packages/core/src/templates/ResourceIssueBoards.ts
  packages/rest/src/index.ts
Labels: type:feature

#3423 Improve docs to highlight supported APIs
  README.md
  packages/cli/README.md
  packages/core/README.md
  packages/core/src/resources/Gitlab.ts
  packages/core/src/resources/index.ts
  packages/requester-utils/README.md
  packages/rest/README.md
  packages/rest/src/index.ts
Labels: type:bug, type:documentation

#3426 Support for endpoint rate limits
  packages/core/src/resources/ApplicationPlanLimits.ts
  packages/core/test/unit/resources/ApplicationPlanLimits.ts
  packages/core/test/unit/resources/ApplicationStatistics.ts
  packages/core/test/unit/resources/Applications.ts
  packages/requester-utils/package.json
  packages/requester-utils/src/BaseResource.ts
  packages/requester-utils/src/RequesterUtils.ts
  packages/requester-utils/test/unit/BaseResource.ts
  packages/requester-utils/test/unit/RequesterUtils.ts
  packages/rest/README.md
  packages/rest/package.json
  packages/rest/src/Requester.ts
  packages/rest/test/e2e/browser/assets/test-import.html
  packages/rest/test/integration/nodejs/resources/Issues.ts
  packages/rest/test/integration/nodejs/resources/Projects.ts
  packages/rest/test/unit/Requester.ts
  yarn.lock
Labels: type:feature

#3430 Fix incorrect HTTP method used in IssueLinks API create method
  packages/core/src/resources/IssueLinks.ts
Labels: type:bug

#3431 Add Missing PaginationRequestOptions in allDiffs and allCommits
  packages/core/src/resources/MergeRequests.ts
Labels: type:bug

#3438 Add support for Service Accounts API
  packages/core/README.md
  packages/core/src/resources/Gitlab.ts
  packages/core/src/resources/GroupServiceAccounts.ts
  packages/core/src/resources/index.ts
  packages/requester-utils/src/RequesterUtils.ts
  packages/requester-utils/test/unit/RequesterUtils.ts
  packages/rest/src/index.ts
Labels: type:feature

#3439 Add approvals property to Deployments Schema
  packages/core/src/resources/Deployments.ts
  packages/requester-utils/test/unit/RequesterUtils.ts
Labels: type:bug

#3441 Updating all dependencies to their latest supported versions
  .gitignore
  .gitlab-ci.yml
  package.json
  packages/cli/package.json
  packages/core/package.json
  packages/core/test/e2e/map.ts
  packages/requester-utils/package.json
  packages/rest/package.json
  packages/rest/test/integration/nodejs/resources/Issues.ts
  yarn.lock
Labels: type:dependencies
