Repository jdalrymple/gitbeaker, pull requests merged in 2023-05, with the labels that each got.

#3235 Update sponsors list
  README.md
  packages/cli/README.md
  packages/core/README.md
  packages/requester-utils/README.md
  packages/rest/README.md
Labels: type:documentation

#3241 Remove usage of skypack for esm.sh
  packages/core/README.md
  packages/requester-utils/README.md
  packages/rest/README.md
  packages/rest/test/e2e/browser/assets/test-import.html
Labels: type:documentation

#3240 Switch from same-origin to cors fetch mode
  packages/rest/src/Requester.ts
  packages/rest/test/unit/Requester.ts
Labels: type:bug

#3244 Fixing support for nested position arguments
  packages/core/src/templates/ResourceDiscussions.ts
  packages/core/test/unit/templates/ResourceDiscussions.ts
Labels: type:bug

#3249 Update fetch mode to exclude cors and add repository unit and integration tests
  packages/core/src/resources/Repositories.ts
  packages/core/test/unit/resources/Repositories.ts
  packages/rest/src/Requester.ts
  packages/rest/test/integration/nodejs/resources/Issues.ts
  packages/rest/test/integration/nodejs/resources/Lint.ts
  packages/rest/test/integration/nodejs/resources/Projects.ts
  packages/rest/test/integration/nodejs/resources/Repositories.ts
  packages/rest/test/unit/Requester.ts
Labels: type:bug

#3258 Settings cors to same-origin conditionally for protected api route
  packages/core/src/resources/Projects.ts
  packages/rest/src/Requester.ts
  packages/rest/test/e2e/browser/resources/Projects.ts
  packages/rest/test/integration/nodejs/resources/Issues.ts
  packages/rest/test/integration/nodejs/resources/Lint.ts
  packages/rest/test/integration/nodejs/resources/Projects.ts
  packages/rest/test/integration/nodejs/resources/Repositories.ts
  packages/rest/test/unit/Requester.ts
Labels: type:hot fix

#3259 Switching buffer response to blob for type consistency in the API
  packages/rest/src/Requester.ts
  packages/rest/test/integration/nodejs/resources/Repositories.ts
  packages/rest/test/unit/Requester.ts
Labels: type:technical debt

#3257 bug: fix contenxt -> content typo
  packages/core/src/resources/Users.ts
Labels: type:bug

#3253 Adding coverage uploads
  .gitignore
  .gitlab-ci.yml
  jest.config.base.mjs
  package.json
Labels: type:technical debt

#3260 Update missing script variable
  .gitlab-ci.yml
Labels: scope:cli, type:bug

#3262 Add missing fields to EditMergeRequestOptions
  packages/core/src/resources/MergeRequests.ts
Labels: type:bug

#3264 docs(package/rest/README.md): fixes invalid orderBy example
  packages/rest/README.md
Labels: type:documentation

#3265 Add MergeRequestNoteAwardEmojis class
  packages/core/src/resources/Gitlab.ts
  packages/core/src/resources/MergeRequestNoteAwardEmojis.ts
  packages/core/src/resources/index.ts
  packages/core/test/e2e/map.ts
  packages/rest/src/index.ts
  packages/rest/test/e2e/browser/index.ts
Labels: type:feature

#3268 Handle casing edge cases
  packages/core/src/resources/IssueLinks.ts
  packages/core/src/resources/LinkedEpics.ts
Labels: type:bug

#3272 Fix typing for Projects, Users and Groups
  packages/core/src/resources/Groups.ts
  packages/core/src/resources/Projects.ts
  packages/core/src/resources/Users.ts
Labels: type:bug

#3275 Added fix for Group Access tokens requests
  packages/core/src/resources/GroupAccessTokens.ts
Labels: type:bug

#3277 Add info about Node v16 support to FAQ
  docs/FAQ.md
Labels: type:documentation

#3278 Updating CI Lint API Support to match Gitlab API v16
  README.md
  packages/core/src/resources/Lint.ts
  packages/rest/README.md
  packages/rest/test/integration/nodejs/resources/Lint.ts
  scripts/docker-compose.yml
Labels: type:bug, type:testing

#3280 Improving pagination types for easier usage
  packages/core/src/infrastructure/RequestHelper.ts
  packages/core/src/infrastructure/Utils.ts
Labels: type:technical debt

#3281 Add missing pagination type exports
  packages/core/src/index.ts
Labels: type:bug
