Repository jdalrymple/gitbeaker, pull requests merged in 2024-10, with the labels that each got.

#3635 Fix Namespace `exists` method typing
  packages/core/src/resources/Namespaces.ts
Labels: type:bug

#3639 Update method for removing invitations
  packages/core/src/templates/ResourceInvitations.ts
Labels: type:bug

#3641 Updating `allowedToCreate` type to an array
  packages/core/src/resources/ProtectedTags.ts
Labels: type:types

#3642 Implement MergeRequests.allIssuesRelated()
  packages/core/src/resources/MergeRequests.ts
  packages/core/test/unit/resources/MergeRequests.ts
Labels: type:feature

#3640 Updating missing expanded types for `Issues.all`
  packages/core/src/resources/Issues.ts
Labels: type:types

#3626 Request Retry Error Message Adjustment
  packages/rest/src/Requester.ts
  packages/rest/test/unit/Requester.ts
Labels: type:enhancement

#3643 Adding support for GroupJobTokenScopes
  .husky/pre-commit
  packages/core/src/resources/Gitlab.ts
  packages/core/src/resources/GroupJobTokenScopes.ts
  packages/core/src/resources/ProjectJobTokenScopes.ts
  packages/core/src/resources/index.ts
  packages/core/src/templates/ResourceJobTokenScopes.ts
  packages/core/src/templates/index.ts
  packages/core/test/integration/map.ts
  packages/core/test/unit/resources/JobTokenScopes.ts
  packages/core/test/unit/templates/ResourceJobTokenScopes.ts
  packages/rest/src/index.ts
  packages/rest/test/e2e/browser/General.ts
  packages/rest/test/integration/browser/General.ts
Labels: breaking, type:feature

#3644 Update `Users.edit` to use FormData when submitting `avatar` updates
  packages/core/src/resources/Users.ts
  packages/core/test/unit/resources/Users.ts
Labels: type:bug
