Repository jdalrymple/gitbeaker, pull requests merged in 2024-05, with the labels that each got.

#3560 Add ServiceAccount creation options
  packages/core/src/resources/GroupServiceAccounts.ts
  packages/core/src/resources/ServiceAccounts.ts
Labels: type:types

#3582 Update visibility typing for Groups and Projects APIs
  packages/core/src/resources/Groups.ts
  packages/core/src/resources/Projects.ts
Labels: type:types

#3583 Updating ProjectSchema to include `marked_for_deletion_on` and adding includeHidden and includePendingDelete to AllProjectOptions
  packages/core/src/resources/Projects.ts
Labels: type:types

#3584 Handling Admin endpoints for the Users API
  packages/core/src/infrastructure/RequestHelper.ts
  packages/core/src/resources/Commits.ts
  packages/core/src/resources/Deployments.ts
  packages/core/src/resources/EpicLinks.ts
  packages/core/src/resources/Epics.ts
  packages/core/src/resources/Events.ts
  packages/core/src/resources/Groups.ts
  packages/core/src/resources/IssueLinks.ts
  packages/core/src/resources/Issues.ts
  packages/core/src/resources/Jobs.ts
  packages/core/src/resources/MergeRequestApprovals.ts
  packages/core/src/resources/MergeRequests.ts
  packages/core/src/resources/MergeTrains.ts
  packages/core/src/resources/PipelineSchedules.ts
  packages/core/src/resources/PipelineTriggerTokens.ts
  packages/core/src/resources/Pipelines.ts
  packages/core/src/resources/ProjectReleases.ts
  packages/core/src/resources/Projects.ts
  packages/core/src/resources/Search.ts
  packages/core/src/resources/Snippets.ts
  packages/core/src/resources/TodoLists.ts
  packages/core/src/resources/Users.ts
  packages/core/src/resources/Webhooks.ts
  packages/core/src/templates/ResourceAwardEmojis.ts
  packages/core/src/templates/ResourceDiscussions.ts
  packages/core/src/templates/ResourceIterationEvents.ts
  packages/core/src/templates/ResourceLabelEvents.ts
  packages/core/src/templates/ResourceMilestoneEvents.ts
  packages/core/src/templates/ResourceNotes.ts
  packages/core/src/templates/ResourceStateEvents.ts
  packages/core/src/templates/ResourceWeightEvents.ts
Labels: type:types

#3588 Remove token requirement to support access without authentication
  packages/requester-utils/src/BaseResource.ts
  packages/requester-utils/src/RequesterUtils.ts
  packages/requester-utils/test/unit/BaseResource.ts
  packages/rest/README.md
Labels: type:feature

#3590 Removing misleading docs from the CLI package README.md
  packages/cli/README.md
Labels: type:documentation

#3585 Add `rebase_in_progress` to `ExpandedMergeRequestSchema`
  packages/core/src/resources/MergeRequests.ts
Labels: type:types

#3589 Fixing missing types reference for shared_with_groups (Groups Schema)
  packages/core/src/resources/Groups.ts
Labels: type:types

#3592 Updating minimum node version and JSON assert keyword
  packages/cli/package.json
  packages/cli/src/cli.ts
  packages/cli/tsconfig.json
  packages/core/package.json
  packages/requester-utils/package.json
  packages/rest/package.json
Labels: type:hot fix

#3594 Fix typo in EpicLabelEvents
  packages/core/src/resources/EpicLabelEvents.ts
Labels: type:bug

#3596 Updating GL version
  .gitlab-ci.yml
Labels: type:testing
