Repository jdalrymple/gitbeaker, pull requests merged in 2024-03, with the labels that each got.

#3550 fix endpoint for removal of remote mirrors
  packages/core/src/resources/ProjectRemoteMirrors.ts
Labels: type:bug

#3547 Allow 'self' for personal access token rotation
  packages/core/src/resources/PersonalAccessTokens.ts
Labels: type:feature

#3546 feat: Implement GitlabPages.showSettings()
  packages/core/src/resources/GitlabPages.ts
Labels: type:feature

#3554 Updating Access Token API wrapper
  packages/core/src/resources/GroupAccessTokens.ts
  packages/core/src/resources/ProjectAccessTokens.ts
  packages/core/src/templates/ResourceAccessTokens.ts
  packages/core/test/unit/templates/ResourceAccessTokens.ts
Labels: breaking, type:enhancement, type:types

#3552 Adding skipci type for rebase
  packages/core/src/resources/MergeRequests.ts
Labels: type:types

#3558 Fixing incorrect Pick typing within the Webhooks API
  packages/core/src/resources/Webhooks.ts
Labels: type:types

#3563 Allow "Any" and "None" for AllMergeRequestsOptions["assigneeId"]
  packages/core/src/resources/MergeRequests.ts
Labels: type:types
