Repository jdalrymple/gitbeaker, pull requests merged in 2024-11, with the labels that each got.

#3651 Add support for topic filtering in `AllGroupProjectsOptions` type
  packages/core/src/resources/Groups.ts
Labels: type:types

#3652 Add options `username` and `expires_at` to DeployTokens.create
  packages/core/src/resources/DeployTokens.ts
  packages/core/test/unit/resources/DeployTokens.ts
Labels: type:enhancement

#3650 Fix ProjectJobTokenScopes to use the correct endpoints
  .yarn/releases/yarn-3.5.0.cjs
  .yarn/releases/yarn-4.0.2.cjs
  .yarn/releases/yarn-4.1.0.cjs
  .yarn/releases/yarn-4.5.1.cjs
  .yarnrc.yml
  package.json
  packages/core/README.md
  packages/core/src/resources/Gitlab.ts
  packages/core/src/resources/GroupJobTokenScopes.ts
  packages/core/src/resources/ProjectJobTokenScopes.ts
  packages/core/src/resources/index.ts
  packages/core/src/templates/ResourceJobTokenScopes.ts
  packages/core/src/templates/index.ts
  packages/core/test/integration/map.ts
  packages/core/test/unit/resources/ProjectJobTokenScopes.ts
  packages/core/test/unit/templates/ResourceJobTokenScopes.ts
  packages/rest/src/index.ts
  packages/rest/test/e2e/browser/General.ts
  packages/rest/test/integration/browser/General.ts
  yarn.lock
Labels: type:bug
