Repository jdalrymple/gitbeaker, pull requests merged in 2024-09, with the labels that each got.

#3622 Adding directory information to the package.json file to fix npm relative path resolution
  packages/cli/package.json
  packages/core/package.json
  packages/requester-utils/package.json
  packages/rest/README.md
  packages/rest/package.json
Labels: type:documentation

#3623 Add sync to ProjectRemoteMirrors (#3616)
  packages/core/src/resources/ProjectRemoteMirrors.ts
Labels: type:feature

#3624 refactor: :label: declare default type first
  packages/core/src/resources/Groups.ts
Labels: type:types

#3627 🐛 Update Deployment.tag to be a boolean.
  packages/core/src/resources/Deployments.ts
Labels: type:types

#3631 feat(jobs): job scope waiting_for_resource
  packages/core/src/resources/Jobs.ts
Labels: type:types

#3632 Fix `upcoming jobs by resource group` endpoint
  packages/core/src/resources/ResourceGroups.ts
Labels: type:bug
