Repository jdalrymple/gitbeaker, pull requests merged in 2024-01, with the labels that each got.

#3508 fix: :bug: bad externUid type
  packages/core/src/resources/Users.ts
Labels: type:bug, type:types

#3428 Update rate limit feature to be more browser freindly
  .all-contributorsrc
  package.json
  packages/core/package.json
  packages/core/src/infrastructure/RequestHelper.ts
  packages/requester-utils/package.json
  packages/requester-utils/src/RequesterUtils.ts
  packages/requester-utils/test/unit/RequesterUtils.ts
  packages/rest/package.json
  packages/rest/src/Requester.ts
  packages/rest/test/e2e/browser/assets/test-import.html
  yarn.lock
Labels: release:canary, type:bug

#3512 Add missing premium/ultimate Project attributes
  packages/core/src/resources/Projects.ts
Labels: type:bug, type:types

#3511 Add typing exports for Webhook Events
  .autorc.yml
  packages/core/src/resources/Projects.ts
  packages/core/src/resources/Webhooks.ts
Labels: type:enhancement, type:types

#3513 Updating Gitbeaker Error typings
  .gitlab-ci.yml
  packages/requester-utils/src/GitbeakerError.ts
  packages/requester-utils/test/unit/GitbeakerError.ts
  packages/rest/src/Requester.ts
Labels: type:bug, type:types

#3514 Fix - export Webhook Interfaces
  packages/core/src/resources/index.ts
Labels: type:bug

#3515 CI/CD Re-organization and Optimization
  .autorc.yml
  .codeclimate.yml
  .eslintignore
  .eslintrc.yml
  .github/ISSUE_TEMPLATE/1-bug.md
  .github/ISSUE_TEMPLATE/2-feature-proposal.md
  .github/ISSUE_TEMPLATE/3-question.md
  .github/ISSUE_TEMPLATE/4-technical-debt.md
  .gitignore
  .gitlab-ci.yml
  .prettierignore
  .yarn/releases/yarn-3.5.0.cjs
  .yarn/releases/yarn-4.0.2.cjs
  .yarnrc.yml
  README.md
  docs/FAQ.md
  docs/TESTING.md
  jest.config.base.mjs
  lerna.json
  lint-staged.config.base.mjs
  nx.json
  package.json
  packages/cli/jest.config.mjs
  packages/cli/lint-staged.config.mjs
  packages/cli/package.json
  packages/cli/tsconfig.json
  packages/core/lint-staged.config.mjs
  packages/core/package.json
  packages/core/test/integration/map.ts
  packages/core/tsconfig.json
  packages/requester-utils/lint-staged.config.mjs
  packages/requester-utils/package.json
  packages/requester-utils/test/unit/BaseResource.ts
  packages/requester-utils/tsconfig.json
  packages/rest/jest.config.mjs
  packages/rest/lint-staged.config.mjs
  packages/rest/package.json
  packages/rest/playwright.config.mjs
  packages/rest/test/assets/test-import.html
  packages/rest/test/e2e/browser/General.ts
  packages/rest/test/e2e/browser/assets/test-import.html
  packages/rest/test/e2e/browser/resources/Projects.ts
  packages/rest/test/e2e/nodejs/resources/Issues.ts
  packages/rest/test/e2e/nodejs/resources/Lint.ts
  packages/rest/test/e2e/nodejs/resources/Projects.ts
  packages/rest/test/e2e/nodejs/resources/Repositories.ts
  packages/rest/test/integration/browser/General.ts
  packages/rest/test/integration/nodejs/General.ts
  packages/rest/tsconfig.json
  prettier.config.cjs
  scripts/shutdown.sh
  yarn.lock
Labels: type:technical debt

#3522 Missing build files
  .gitlab-ci.yml
  packages/cli/package.json
  packages/core/package.json
  packages/rest/package.json
  yarn.lock
Labels: release:canary

#3528 Changing project create types for path and name
  packages/core/src/infrastructure/Utils.ts
  packages/core/src/resources/Projects.ts
Labels: type:types

#3529 Set timeout on e2e test setup job to avoid long CI builds
  .gitlab-ci.yml
Labels: type:technical debt
