Repository jdalrymple/gitbeaker, pull requests merged in 2025-03, with the labels that each got.

#3693 Adding missing Id attribute to the WebhookUserSchema
  packages/core/src/resources/Webhooks.ts
Labels: type:types

#3695 Make an Issues milestone property optional
  packages/core/src/resources/Issues.ts
Labels: type:types

#3697 Fixing typo in CreateAndEditPushRuleOptions
  packages/core/src/templates/ResourcePushRules.ts
Labels: type:types

#3696 Support ci_pipeline_variables_minimum_override_role in the Projects API
  packages/core/src/resources/Projects.ts
Labels: type:types

#3694 Make offset pagination for listing all CI Pipelines explicit
  packages/core/src/resources/Pipelines.ts
Labels: type:types

#3690 Export error classes in rest package
  packages/rest/src/index.ts
  packages/rest/test/integration/browser/General.ts
Labels: type:enhancement

#3701 Added masked_and_hidden option to the ProjectVariables
  packages/core/src/resources/ProjectVariables.ts
Labels: type:types

#3703 fix: Typing of Error description can be incorrect depending on the respose payload
  packages/rest/src/Requester.ts
  packages/rest/test/unit/Requester.ts
  packages/rest/test/utils/index.ts
Labels: type:bug
