Repository jdalrymple/gitbeaker, pull requests merged in 2025-07, with the labels that each got.

#3736 Move maxPages under BasePaginationRequestOptions
  packages/core/src/infrastructure/RequestHelper.ts
Labels: type:types

#3733 Set merge request `description` type to nullable
  packages/core/src/resources/MergeRequests.ts
Labels: type:types

#3732 Fix includeDivergedCommitsCount Type Definition
  packages/core/src/resources/MergeRequests.ts
Labels: type:types

#3737 Add support for Markdown Uploads
  .gitignore
  packages/core/README.md
  packages/core/src/resources/Gitlab.ts
  packages/core/src/resources/GroupMarkdownUploads.ts
  packages/core/src/resources/ProjectMarkdownUploads.ts
  packages/core/src/resources/index.ts
  packages/core/src/templates/ResourceMarkdownUploads.ts
  packages/core/src/templates/index.ts
  packages/core/test/integration/map.ts
  packages/core/test/unit/resources/ProjectMarkdownUploads.ts
  packages/core/test/unit/templates/ResourceMarkdownUploads.ts
  packages/requester-utils/package.json
  packages/rest/src/index.ts
  packages/rest/test/integration/browser/General.ts
Labels: type:feature

#3743 fix: Mapping export is incorrectly generating argument lists
  packages/cli/src/cli.ts
  packages/cli/src/utils.ts
  packages/core/package.json
  packages/core/scripts/generate.ts
  packages/core/scripts/getParamNames.ts
  yarn.lock
Labels: type:bug

#3744 fix: Incorrect camelization when passing properties to the CLI
  packages/cli/src/cli.ts
  packages/cli/src/utils.ts
Labels: type:bug

#3746 fix: Parsing param names from functions with destructured params was not working correctly
  packages/core/scripts/getParamNames.ts
Labels: type:bug

#3747 tests: Recent resources added were missing from e2e tests
  packages/rest/test/e2e/browser/General.ts
Labels: type:testing

#3749 fix(core): Rename projectId to groupId in types
  packages/core/src/resources/GroupLabels.ts
Labels: type:types

#3750 docs: Renamed Gitlab to GitLab
  .gitlab-ci.yml
  README.md
  docs/FAQ.md
  docs/TESTING.md
  packages/cli/src/utils.ts
  packages/core/src/resources/MergeRequests.ts
  packages/rest/README.md
Labels: type:documentation
