Repository jdalrymple/gitbeaker, pull requests merged in 2025-05, with the labels that each got.

#3715 Fix argument names for ProtectedEnvironments
  packages/core/src/resources/GroupProtectedEnvironments.ts
  packages/core/src/resources/ProjectProtectedEnvironments.ts
  packages/core/src/templates/ResourceProtectedEnvironments.ts
  packages/core/test/unit/templates/ResourceProtectedEnvironments.ts
  packages/rest/test/unit/Requester.ts
Labels: type:bug

#3720 Limit pipeline usage to MRs
  .gitlab-ci.yml
Labels: type:technical debt

#3725 Add missing `merge_request` field to WebhookEmojiEventSchema
  packages/core/src/resources/Webhooks.ts
Labels: type:types
