Repository jdalrymple/gitbeaker, pull requests merged in 2025-08, with the labels that each got.

#3754 Add support for MergeRequestStateEvents
  packages/core/src/resources/Gitlab.ts
  packages/core/src/resources/MergeRequestStateEvents.ts
  packages/core/test/unit/resources/MergeRequestStateEvents.ts
Labels: type:feature

#3753 Add rate limit duration
  packages/requester-utils/src/BaseResource.ts
  packages/requester-utils/src/RequesterUtils.ts
  packages/requester-utils/test/unit/RequesterUtils.ts
  packages/rest/README.md
Labels: type:feature

#3756 Addressing security alert through updating affected packages
  .gitlab-ci.yml
  .yarn/releases/yarn-4.6.0.cjs
  .yarn/releases/yarn-4.9.2.cjs
  .yarnrc.yml
  package.json
  packages/cli/package.json
  packages/core/package.json
  packages/requester-utils/package.json
  packages/rest/package.json
  yarn.lock
Labels: type:security, type:dependencies

#3758 Add ciDeletePipeLineInSeconds to CreateProjectOptions
  packages/core/src/resources/Projects.ts
  packages/core/test/unit/resources/Projects.ts
Labels: type:types

#3757 Add support for EpicStateEvents
  packages/core/src/resources/EpicStateEvents.ts
  packages/core/src/resources/Gitlab.ts
  packages/core/test/unit/resources/EpicStateEvents.ts
Labels: type:feature
